# Site settings
title: Aaron Li
description: Aaron Li's Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaron Li
user_description: A Toronto based developer studying at the University of Toronto
user_title: Software Developer
email: aaronhf.li@mail.utoronto.ca
twitter_username: lorem_ipsum
github_username:  ALProjects
linkedIn_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
